openapi: 3.0.0
info:
  version: 1.0.0
  title: Api endpoint

paths:
  /test:
    post:
      tags:
        - test
      summary: Test api endpoint
      operationId: api.views.test
      responses:
        200:
          description: success
